### ISSUE TITLE
Improving the Readme.md file

### ISSUE THREAD

**Issue by ayushkumarbhadani** [Deveimer/vovoca-frontend#16] opened 2023-05-26 03:29 UTC
There is a spelling mistake in the readme.md file of this repository.  "Trednding Music" is written instead of "Trending Music"

Assign this task to me under GSSOC23 Label, please.

**Comment by varun-singhh** [comment] 2023-05-26 05:21
assigned

**Comment by Eiman-Zulfiqar** [comment] 2023-05-26 09:00
Hey, I do like to contribute as I see the grammatical and punctuation mistakes in the readme file, especially in the contributors sections. This is making the file difficult to be read. 

e.g. If you made up you mind to contribute the fork the repository and star it

**Comment by Eiman-Zulfiqar** [comment] 2023-05-26 09:01
Assign this task to me under gssoc23 label.

**Comment by varun-singhh** [comment] 2023-05-26 09:20
@Eiman-Zulfiqar it's already assigned to @ayushkumarbhadani if the issue is not resolved by deadline I will assign it to you. You can see the deadline in the due date section under projects on right side of the page.

**Comment by ayushkumarbhadani** [comment] 2023-05-26 12:32
@varun-singhh Check the PR please: #23

**Comment by varun-singhh** [comment] 2023-05-26 17:25
@ayushkumarbhadani please resolve the comments on PR

**Comment by ayushkumarbhadani** [comment] 2023-05-26 17:58
Hey @varun-singhh, can you please elaborate on which comments are you talking about? I didn't get you.

**Comment by varun-singhh** [comment] 2023-05-27 15:27
> Hey @varun-singhh, can you please elaborate on which comments are you talking about? I didn't get you.

the PR which you raised

**Comment by ayushkumarbhadani** [comment] 2023-05-27 15:31
> > Hey @varun-singhh, can you please elaborate on which comments are you talking about? I didn't get you.
> 
> the PR which you raised

@varun-singhh Everything looks good to me! I can't see any comments that need to be resolved. 🤔



<img width="933" alt="Screenshot 2023-05-27 at 9 00 57 PM" src="https://github.com/Deveimer/vovoca-frontend/assets/73775939/5c82534a-398f-401d-9c5c-3e2bf4f9cf94">

**Closed as completed** 2023-05-27 15:43 UTC
Labels: gssoc23, level1
